### ISSUE TITLE
Frigidaire no longer working after HA update?

### ISSUE THREAD

**Issue by ha-elguano** [bm1549/home-assistant-frigidaire#28]
After the latest HA update, the Frigidaire component no longer seems to load:

> Home Assistant 2023.5.0
> Supervisor 2023.04.1
> Operating System 10.1
> Frontend 20230503.1 - latest

Here is the error from the HA log snippet:

> Logger: homeassistant.config_entries
> Source: custom_components/frigidaire/__init__.py:32
> Integration: frigidaire
> First occurred: 12:32:26 AM (2 occurrences)
> Last logged: 7:14:44 AM
> 
> Error setting up entry frigidaire for frigidaire
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
>     result = await component.async_setup_entry(hass, self)
>   File "/config/custom_components/frigidaire/__init__.py", line 32, in async_setup_entry
>     hass.config_entries.async_setup_platforms(entry, PLATFORMS)
> AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by ha-elguano** [comment]
I've resolved it, but not sure how. I did a few things, including conforming the last weeks' changes in custom_components (which only incremented the app version number) and reset my password in Frigidaire's app/server. Re-installing the integration seems to have fixed it. I think this may have been related to Frigidaire's recent app/password update requirements.
