### ISSUE TITLE
Error setting up entry frigidaire for frigidaire

### ISSUE THREAD

**Issue by justinmyersm** [bm1549/home-assistant-frigidaire#32]
Recently updated to HA 2023.5.3 and am no longer able to use the Frigidaire integration. Reloading the integration nor rebooting resolves the issue. 

```
Home Assistant 2023.5.3
Supervisor 2023.04.1
Operating System 10.1
```

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/frigidaire/__init__.py:32
Integration: frigidaire
First occurred: 10:04:29 AM (1 occurrences)
Last logged: 10:04:29 AM

Error setting up entry frigidaire for frigidaire
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/frigidaire/__init__.py", line 32, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'
```

**Comment by thejevans** [comment]
Please update the repository to the most recent commit. This has been fixed.

**Comment by justinmyersm** [comment]
Apologies! It did indeed fix the issue. Thank you.
