### ISSUE TITLE
Frigidaire failing to configure/reconfigure

### ISSUE THREAD

**Issue by justinmyersm** [bm1549/home-assistant-frigidaire#44]
Core - 2024.1.3
Supervisor - 2023.12.1
Operating System - 11.4
Frontend - 20240104.0

Logger: homeassistant.config_entries
Source: config_entries.py:406
First occurred: 12:16:51 AM (3 occurrences)
Last logged: 9:10:14 AM

Error setting up entry frigidaire for frigidaire
Traceback (most recent call last):
  File "/config/custom_components/frigidaire/__init__.py", line 20, in setup
    hass.data[DOMAIN][entry.entry_id] = frigidaire.Frigidaire(
                                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frigidaire/__init__.py", line 246, in __init__
    self.authenticate()
  File "/usr/local/lib/python3.11/site-packages/frigidaire/__init__.py", line 282, in authenticate
    auth_response = self.post_request('/authentication/authenticate', data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frigidaire/__init__.py", line 430, in post_request
    return self.parse_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/frigidaire/__init__.py", line 404, in parse_response
    raise FrigidaireException(f'Request failed with status {response.status_code}: {response.content}')
frigidaire.FrigidaireException: Request failed with status 403: b'{"message":"Forbidden"}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frigidaire/__init__.py", line 28, in async_setup_entry
    await hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/frigidaire/__init__.py", line 26, in setup
    raise data_entry_flow.AbortFlow from err
TypeError: AbortFlow.__init__() missing 1 required positional argument: 'reason'

**Comment by ha-elguano** [comment]
I've been running into the same thing--"integration fails to setup," "needs attention."

**Comment by mefbgil** [comment]
Same here.  I have a dehumidifier that I deleted because it wasn't connected, and now can't re-add it.

**Comment by amaisano** [comment]
I think this is mine as well. The 403 with the 'reason' message.

**Comment by amaisano** [comment]
After 24 hours, new entities popped up. I haven't used the integration for a few months, so maybe that's why the old entities didn't work? The new entities (climate.office_ac_2 as the new version of climate.office_ac) seems work, but the temperature scale is in F instead of C. That's a different issue. 

The issue here for me has cleared up.
